### ISSUE TITLE
Can't import minimal8team on develop branch

### ISSUE THREAD

**Issue by franga2000** [TabbycatDebate/tabbycat#2268]
On the current `develop` branch, importing the `minimal8team` fixture crashes with a `KeyError('seq')`.

<details>
<summary>Full stack trace</summary>

```
[2023-02-27 02:45:18,844] ERROR django.request: Internal Server Error: /load-demo/
Traceback (most recent call last):
  File "/home/franga2000/.local/share/virtualenvs/tabbycat-JNF0467W/lib/python3.10/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/home/franga2000/.local/share/virtualenvs/tabbycat-JNF0467W/lib/python3.10/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/franga2000/.local/share/virtualenvs/tabbycat-JNF0467W/lib/python3.10/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/franga2000/.local/share/virtualenvs/tabbycat-JNF0467W/lib/python3.10/site-packages/django/contrib/auth/mixins.py", line 128, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/franga2000/.local/share/virtualenvs/tabbycat-JNF0467W/lib/python3.10/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/franga2000/DEV/tabbycat/tabbycat/importer/views.py", line 226, in post
    management.call_command(importtournament.Command(), source,
  File "/home/franga2000/.local/share/virtualenvs/tabbycat-JNF0467W/lib/python3.10/site-packages/django/core/management/__init__.py", line 181, in call_command
    return command.execute(*args, **defaults)
  File "/home/franga2000/.local/share/virtualenvs/tabbycat-JNF0467W/lib/python3.10/site-packages/django/core/management/base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "/home/franga2000/DEV/tabbycat/tabbycat/importer/management/commands/importtournament.py", line 74, in handle
    self.make(item)
  File "/home/franga2000/DEV/tabbycat/tabbycat/importer/management/commands/importtournament.py", line 162, in make
    import_method(f)
  File "/home/franga2000/DEV/tabbycat/tabbycat/importer/importers/anorak.py", line 330, in import_motions
    self._import(f, mm.RoundMotion, round_motions_interpreter)
  File "/home/franga2000/DEV/tabbycat/tabbycat/importer/importers/base.py", line 230, in _import
    kwargs_list = list(kwargs_list) # force evaluation
  File "/home/franga2000/DEV/tabbycat/tabbycat/importer/importers/anorak.py", line 323, in round_motions_interpreter
    for round_name, seq in zip(line['rounds'].split(";"), line['seq'].split(";")):
KeyError: 'seq'
[2023-02-27 02:45:18,849] ERROR django.channels.server: HTTP POST /load-demo/ 500 [1.21, 127.0.0.1:45910]
```

</details>

It looks like the other examples have a `seq` column in the `motions.csv` file and `minimal8team` doesn't, but I'm not sure what the best way to fix this is as I'm not familiar with the "anorak" format or the importer architecture in general.

**Comment by tienne-B** [comment]
I don't think you're up-to-date in `develop`, as this issue was fixed in 1fa189edf2c6bf347e984ac00499128784ea0011. Note that `tabbycat/importer/importers/anorak.py:323` is different between the commit and your stacktrace.
