### ISSUE TITLE
Deployment via Github Issue on Heroku

### ISSUE THREAD

**Issue by cringenotunfunny** [TabbycatDebate/tabbycat#2489]
Generates a domain, but fails to push the deployment
Activity Log:

-----> Building on the Heroku-22 stack
-----> Determining which buildpack to use for this app
 !     Warning: Multiple default buildpacks reported the ability to handle this app. The first buildpack in the list below will be used.
			Detected buildpacks: Python,Node.js
			See https://devcenter.heroku.com/articles/buildpacks#buildpack-detect-order
-----> Python app detected
-----> Using Python version specified in runtime.txt
-----> Installing python-3.11.9
-----> Installing pip 24.0, setuptools 70.3.0 and wheel 0.43.0
-----> Installing dependencies with Pipenv 2024.0.1
       Installing dependencies from Pipfile.lock (975a4d)...
-----> Installing SQLite3
-----> $ python tabbycat/manage.py collectstatic --noinput
       2024-08-15 07:59:28,634 - root - INFO - SPLIT_SETTINGS: imported local.py
       Traceback (most recent call last):
         File "/tmp/build_d131fdf5/tabbycat/manage.py", line 18, in <module>
           execute_from_command_line(sys.argv)
         File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
           utility.execute()
         File "/app/.heroku/python/lib/python3.11/site-packages/django/core/management/__init__.py", line 382, in execute
           settings.INSTALLED_APPS
         File "/app/.heroku/python/lib/python3.11/site-packages/django/conf/__init__.py", line 89, in __getattr__
           self._setup(name)
         File "/app/.heroku/python/lib/python3.11/site-packages/django/conf/__init__.py", line 76, in _setup
           self._wrapped = Settings(settings_module)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.11/site-packages/django/conf/__init__.py", line 190, in __init__
           mod = importlib.import_module(self.SETTINGS_MODULE)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "/app/.heroku/python/lib/python3.11/importlib/__init__.py", line 126, in import_module
           return _bootstrap._gcd_import(name[level:], package, level)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
         File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
         File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
         File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
         File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
         File "<frozen importlib._bootstrap_external>", line 940, in exec_module
         File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
         File "/tmp/build_d131fdf5/tabbycat/settings/__init__.py", line 44, in <module>
           include(*base_settings)
         File "/app/.heroku/python/lib/python3.11/site-packages/split_settings/tools.py", line 97, in include
           raise OSError('No such file: {0}'.format(pattern))
       OSError: No such file: /tmp/build_d131fdf5/tabbycat/settings/local.py
 !     Error while running '$ python tabbycat/manage.py collectstatic --noinput'.
       See traceback above for details.
       You may need to update application code to resolve this error.
       Or, you can disable collectstatic for this application:
          $ heroku config:set DISABLE_COLLECTSTATIC=1
       https://devcenter.heroku.com/articles/django-assets
 !     Push rejected, failed to compile Python app.
 !     Push failed

**Comment by cringenotunfunny** [comment]
Push fails even on Heroku CLI

<img width="846" alt="HerokuErrorCLI" src="https://github.com/user-attachments/assets/e3a6883d-ca17-4b55-a0b3-538dfe7a2a54">
