### ISSUE TITLE
Getting Error while trying to deploy in Heroku

### ISSUE THREAD

**Issue by Taraldinn** [TabbycatDebate/tabbycat#2539]
I was trying to deploy in heroku via command prompt deploy_heroku script but this scipt is not working and geeting this error . the exact error shown in bellow . 

```bash


PS F:\code\tabbycat> git checkout master
branch 'master' set up to track 'origin/master'.
Switched to a new branch 'master'
PS F:\code\tabbycat> python deploy_heroku.py -
$ heroku apps:create --stack heroku-22 --addons papertrail,heroku-postgresql:essential-0,rediscloud:30,heroku-redis:mini
Creating app... done, guarded-reaches-93196, stack is heroku-22
Adding papertrail... done
Adding heroku-postgresql:essential-0... done
Adding rediscloud:30... done
Adding heroku-redis:mini... done
https://guarded-reaches-93196-e6c648abce7b.herokuapp.com/ | https://git.heroku.com/guarded-reaches-93196.git
$ heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nginx.git --app guarded-reaches-93196
Buildpack set. Next release on guarded-reaches-93196 will use https://github.com/heroku/heroku-buildpack-nginx.git.
Run git push heroku main to create a new release using this buildpack.
$ heroku buildpacks:add heroku/nodejs --app guarded-reaches-93196
Buildpack added. Next release on guarded-reaches-93196 will use:
  1. https://github.com/heroku/heroku-buildpack-nginx.git
  2. heroku/nodejs
Run git push heroku main to create a new release using these buildpacks.
$ heroku buildpacks:add heroku/python --app guarded-reaches-93196
Buildpack added. Next release on guarded-reaches-93196 will use:
  1. https://github.com/heroku/heroku-buildpack-nginx.git
  2. heroku/nodejs
  3. heroku/python
Run git push heroku main to create a new release using these buildpacks.
$ heroku config:set DISABLE_COLLECTSTATIC=1 ON_HEROKU=1 USING_NGINX=1 DJANGO_SECRET_KEY="ftjl&9%-nz4lz5xm*(dx0wd1-29^9n3dk_&o5$@qh)kv(lynp4" DEBUG=0 TIME_ZONE=Australia/Melbourne --app guarded-reaches-93196
Setting DISABLE_COLLECTSTATIC, ON_HEROKU, USING_NGINX, DJANGO_SECRET_KEY, DEBUG, TIME_ZONE and restarting ⬢ guarded-reaches-93196... done, v5
DEBUG:                 0
DISABLE_COLLECTSTATIC: 1
DJANGO_SECRET_KEY:     "ftjl&9%-nz4lz5xm*(dx0wd1-29^9n3dk_&o5$@qh)kv(lynp4"
ON_HEROKU:             1
TIME_ZONE:             Australia/Melbourne
USING_NGINX:           1
Waiting for Heroku Redis to provision (may take up to 5 minutes)...
Traceback (most recent call last):
  File "F:\code\tabbycat\deploy_heroku.py", line 214, in <module>
    redis_output = subprocess.check_output(redis_status_command).decode().split("\n")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazif\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazif\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kazif\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\kazif\AppData\Local\Programs\Python\Python312\Lib\subprocess.py", line 1538, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [WinError 2] The system cannot find the file specified

```

**Comment by tienne-B** [comment]
Try running the script using WSL2?
