### ISSUE TITLE
Creating tournament using simple importer fails with TemplateSyntaxError

### ISSUE THREAD

**Issue by tienne-B** [TabbycatDebate/tabbycat#559]
Trying to access http://localhost:8000/create/ locally on macOS (Django 2.0), a TemplateSyntaxError exception was raised about the use of tournamenturl in the sidebar. The message was "tournamenturl can only be used in contexts with a tournament rtf" as defined on line 65 of debate_tags.py.

**Comment by czlee** [comment]
Thanks for reporting this! That's weird, any chance you could include a stacktrace?

**Comment by tienne-B** [comment]
```
[2018-02-13 22:04:24,468] ERROR django.request: Internal Server Error: /create/
Traceback (most recent call last):
  File "/Users/etienne/Git/tabbycat/tabbycat/utils/templatetags/debate_tags.py", line 63, in render
    tournament_slug = context['tournament'].slug
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/context.py", line 83, in __getitem__
    raise KeyError(key)
KeyError: 'tournament'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/core/handlers/exception.py", line 35, in inner
    response = get_response(request)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 158, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/channels/handler.py", line 243, in process_exception_by_middleware
    return super(AsgiHandler, self).process_exception_by_middleware(exception, request)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/core/handlers/base.py", line 156, in _get_response
    response = response.render()
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/response.py", line 106, in render
    self.content = self.rendered_content
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/response.py", line 83, in rendered_content
    content = template.render(context, self._request)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/backends/django.py", line 61, in render
    return self.template.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 175, in render
    return self._render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 155, in render
    return compiled_parent._render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/defaulttags.py", line 314, in render
    return nodelist.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 67, in render
    result = block.nodelist.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/loader_tags.py", line 194, in render
    return template.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 177, in render
    return self._render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 167, in _render
    return self.nodelist.render(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 943, in render
    bit = node.render_annotated(context)
  File "/Users/etienne/Git/tabbycat/venv/lib/python3.5/site-packages/django/template/base.py", line 910, in render_annotated
    return self.render(context)
  File "/Users/etienne/Git/tabbycat/tabbycat/utils/templatetags/debate_tags.py", line 65, in render
    raise TemplateSyntaxError("tournamenturl can only be used in contexts with a tournament rtf ")
django.template.exceptions.TemplateSyntaxError: tournamenturl can only be used in contexts with a tournament rtf 
```

**Comment by philipbelesky** [comment]
Hi @tienne-B thanks for letting us know about this. As best as I can tell you are running the `develop` branch of Tabbycat which sometimes has bugs such as this given we use it as our work-in-progress branch. 

Could you confirm that you are running from `develop` (did you download a zip or use git?). I would recommend also switching to running from `master` if you either want to use a local copy for a real tournament or get a feel for how the software works. Let me know if you need a hand switching over to master — it will require re-running a lot of the setup instructions like `pip install` / `npm install` etc

**Comment by philipbelesky** [comment]
Alternately if you're keen to keep running on `develop` bug reports such as these are much appreciated! This and the other issue you reported should be fixed now.

**Comment by philipbelesky** [comment]
I'm presuming this should be closed as you either switcher to master or updated develop. Let me know if that's not the case!
